---
abstract: 'Add directory trees to the C<@INC> array at compile time.'
author:
  - 'Calvin Schwenzfeier <calvin.schwenzfeier@gmail.com>'
build_requires:
  Config: Carp
  ExtUtils::MakeMaker: 6.42
  File::Path: 0
  File::Spec: Cwd
  Test::More: IO::Handle
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lib-tree
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
